### PR TITLE
Add remaining common functionality

### PR DESCRIPTION
**Pull request by fureigh**
Fixes issue #3.

Changes proposed in this pull request:
- Add/restore remaining functionality.
- Turn off CSS and JS preprocessing for now, to avoid unnecessary gotchas in front-end development.

### CODE REVIEW

**Comment by fureigh** [comment]
@lindsayyoung, want to take this branch for a spin?

**Comment by fureigh** [comment]
(If you don't want to lose your local content and config, export and save them before trying this. Otherwise they'll get blown away.)

**Comment by pburkholder** [comment]
Should the files in
`web/sites/default/files/php/cache_data` be gitignored ?

**Comment by fureigh** [comment]
@pburkholder I believe so, good catch! That's a holdover from 92d6cc935734cb93475f387048c82066ed4afaa2.

**Comment by fureigh** [comment]
Should look a little something like this:

screenshot of the proposed result (with edited body)

...without the body text, which I added locally.

**Comment by LindsayYoung** [comment]
This did bring back the ability to post content locally and on [cloud.gov](https://web-exhausted-rabbit.app.cloud.gov/hello-world) 🎉 

I am noting a few small things, that could be follow up PRs and I would be happy to chip in. Tell me if you want me to write up issues I think I almost have my Drupal sea legs.

The action drop down menu in content tab is missing options:

Screen Shot 2019-04-03 at 4 10 31 PM

I had an issue with the local media upload but it works on cloud.gov, so I am not really concerned for now. (Also that may not be this branch, I needed the local s3 branch to run it)

Thank you again!

**Comment by fureigh** [comment]
Good catch, @LindsayYoung! I'll check on media upload, but actions should be working now:

action options

confirmation that an action completed

**Comment by fureigh** [comment]
@LindsayYoung I'm not able to replicate the media uploading issue — as you said, it could be an artifact of combining branches. Mind filing a separate issue with steps to reproduce?

uploaded media locally

Incidentally, if `/admin/reports/dblog` isn't already on your radar, it's often a useful place to look when troubleshooting.

Seems like we're good to merge this one, then, yes?

**Comment by LindsayYoung** [comment]
I can confirm that this functionality works for me too. Thank you @fureigh !

I will make a separate issue for the local file.

**Pull request merged**
